INSERT INTO departments (dept_name)
VALUES
  ('Human Resources'),
  ('Finances'),
  ('Operations and Management'),
  ('Advertisement'),
  ('Engineering'),



INSERT INTO roles (title, salary)
VALUES
  ('Manager', 70000),
  ('Engineer', 85000),
  ('Associate', 45000),
  ('Coordinator' 55000),
  ('Assistant', 35000),
  ('Director', 90000),


INSERT INTO voters (first_name, last_name)
VALUES
  ('James', 'Fraser'),
  ('Jack', 'London'),
  ('Robert', 'Bruce'),
  ('Peter', 'Greenaway'),
  ('Derek', 'Jarman'),
  ('Paolo', 'Pasolini'),
  ('Heathcote', 'Williams'),
  ('Sandy', 'Powell'),
  ('Emil', 'Zola'),
  ('Sissy', 'Coalpits'),
  ('Antoinette', 'Capet'),
  ('Samuel', 'Delany'),
  ('Tony', 'Duvert'),
  ('Dennis', 'Cooper'),
  ('Monica', 'Bellucci'),
  ('Samuel', 'Johnson'),
  ('John', 'Dryden'),
  ('Alexander', 'Pope'),
  ('Lionel', 'Johnson'),
  ('Aubrey', 'Beardsley'),
  ('Tulse', 'Luper'),
  ('William', 'Morris'),
  ('George', 'Shaw'),
  ('Arnold', 'Bennett'),
  ('Algernon', 'Blackwood'),
  ('Rhoda', 'Broughton'),
  ('Hart', 'Crane'),
  ('Vitorio', 'DeSica'),
  ('Wilkie', 'Collins'),
  ('Elizabeth', 'Gaskell'),
  ('George', 'Sand'),
  ('Vernon', 'Lee'),
  ('Arthur', 'Machen'),
  ('Frederick', 'Marryat'),
  ('Harriet', 'Martineau'),
  ('George', 'Meredith'),
  ('Margaret', 'Oliphant'),
  ('Anthony', 'Trollope'),
  ('Charlotte', 'Yonge'),
  ('Horace', 'Walpole'),
  ('Matthew', 'Lewis'),
  ('William', 'Bedford'),
  ('Anne', 'Radcliffe'),
  ('Charles', 'Brown'),
  ('Eliza', 'Parsons'),
  ('Susan', 'Hill'),
  ('Sydney', 'Owenson'),
  ('Hubert', 'Crackanthorpe'),
  ('William', 'Carleton'),
  ('Gerald', 'Griffin');

